### ISSUE TITLE
Snowcast error for hazelcastClient configuration

### ISSUE THREAD

**Issue by mozinrat** [noctarius/snowcast#15]
Can you please help with below error which I started getting now in an existing code, we are using 

```
Snowcast snowcast = SnowcastSystem.snowcast(hazelcastClient);

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.noctarius.snowcast.SnowcastSequencer]: Factory method 'snowcastSequencer' threw exception; nested exception is java.lang.VerifyError: class com.noctarius.snowcast.impl.operations.client.ClientRemoveChannelOperation overrides final method call.()Ljava/lang/Object;
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    ... 49 more
Caused by: java.lang.VerifyError: class com.noctarius.snowcast.impl.operations.client.ClientRemoveChannelOperation overrides final method call.()Ljava/lang/Object;
    at java.lang.ClassLoader.defineClass1(Native Method)
```

Thanks for help

**Comment by noctarius** [comment]
Which version of Hazelcast do you try to use?

**Comment by mozinrat** [comment]
I have used 3.5.4, is it supported?
Any ideas??

**Comment by mozinrat** [comment]
It seems there is an incompatibility issue with hazelcast 3.5.1+. Are you working on this.

**Comment by noctarius** [comment]
Let me look into this over the weekend, needs to see how to actually fix this.

**Comment by mozinrat** [comment]
@noctarius did you get chance to see how to make snowcast work with version 3.5.4(prod release). V 3.5.1 has some bugs and its hard to stick to it.

**Comment by noctarius** [comment]
Hey there @mozinrat, sorry for the late answer. I guess I fixed it but the internal API changed again, a fuc.... nightmare -.-

Can you please compile and test latest master? (Fixing commit https://github.com/noctarius/snowcast/commit/1f037a102fc1f6fc1bb80f81577718bee630d10d)

If everything's ok I would release it as 1.0.0 GA, since 3.6 will need a lot of additional changes (from my first look).

**Comment by noctarius** [comment]
snowcast 1.0.0-RC4 released, maven central sync scheduled :)

I'm going to close the issue for now, feel free to reopen if bug persists.
