### ISSUE TITLE
serializer exception "There is no suitable serializer for class com.noctarius.snowcast.impl.SequencerDefinition"

### ISSUE THREAD

**Issue by igool** [noctarius/snowcast#16]
# some exception throws.

WARNING: [192.168.1.49]:5701 [dev] [3.5.5] There is no suitable serializer for class com.noctarius.snowcast.impl.SequencerDefinition
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable serializer for class com.noctarius.snowcast.impl.SequencerDefinition
 at com.hazelcast.nio.serialization.SerializationServiceImpl.serializerFor(SerializationServiceImpl.java:469)
 at com.hazelcast.nio.serialization.SerializationServiceImpl.writeObject(SerializationServiceImpl.java:303)
 at com.hazelcast.nio.serialization.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:315)
 at com.noctarius.snowcast.impl.LogicalNodeTable.writeLogicalNodeTable(LogicalNodeTable.java:177)
 at com.noctarius.snowcast.impl.PartitionReplication.writeData(PartitionReplication.java:68)
 at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:140)
 at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:39)
 at com.hazelcast.nio.serialization.StreamSerializerAdapter.write(StreamSerializerAdapter.java:37)
 at com.hazelcast.nio.serialization.SerializationServiceImpl.writeObject(SerializationServiceImpl.java:305)
 at com.hazelcast.nio.serialization.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:315)
 at com.noctarius.snowcast.impl.operations.SequencerReplicationOperation.writeInternal(SequencerReplicationOperation.java:70)
 at com.hazelcast.spi.Operation.writeData(Operation.java:440)
 at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:140)
 at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:39)
 at com.hazelcast.nio.serialization.StreamSerializerAdapter.write(StreamSerializerAdapter.java:37)
 at com.hazelcast.nio.serialization.SerializationServiceImpl.writeObject(SerializationServiceImpl.java:305)
 at com.hazelcast.nio.serialization.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:315)
 at com.hazelcast.partition.impl.MigrationOperation.writeInternal(MigrationOperation.java:216)
 at com.hazelcast.spi.Operation.writeData(Operation.java:440)
 at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:140)
 at com.hazelcast.nio.serialization.DataSerializer.write(DataSerializer.java:39)
 at com.hazelcast.nio.serialization.StreamSerializerAdapter.write(StreamSerializerAdapter.java:37)
 at com.hazelcast.nio.serialization.SerializationServiceImpl.toData(SerializationServiceImpl.java:227)
 at com.hazelcast.nio.serialization.SerializationServiceImpl.toData(SerializationServiceImpl.java:207)
 at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:197)
 at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:357)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeRemote(Invocation.java:253)
 at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:229)

**Comment by noctarius** [comment]
Sorry for the late answer, did you manage to get this going?
